export type SignLanguage = {
  id: string;
  name: string;
  nativeName: string;
  region: string;
  code: string;
  spokenLang: string;
  speechLang: string;
};

/** Major signed languages worldwide (ISO 639-3 / common codes where available). */
export const SIGN_LANGUAGES: SignLanguage[] = [
  // South Asia (priority for Knight Vision)
  {
    id: "isl",
    name: "Indian Sign Language",
    nativeName: "भारतीय सांकेतिक भाषा",
    region: "South Asia",
    code: "ins",
    spokenLang: "English / Hindi",
    speechLang: "en-IN",
  },
  {
    id: "psl",
    name: "Pakistani Sign Language",
    nativeName: "پاکستانی اشاروں کی زبان",
    region: "South Asia",
    code: "pks",
    spokenLang: "Urdu / English",
    speechLang: "en-IN",
  },
  {
    id: "bansl",
    name: "Bangladeshi Sign Language",
    nativeName: "বাংলাদেশী ইশারা ভাষা",
    region: "South Asia",
    code: "bds",
    spokenLang: "Bengali / English",
    speechLang: "en-IN",
  },
  {
    id: "ssl-lk",
    name: "Sri Lankan Sign Language",
    nativeName: "Sri Lanka Sign Language",
    region: "South Asia",
    code: "sqs",
    spokenLang: "Sinhala / English",
    speechLang: "en-IN",
  },
  {
    id: "nsl",
    name: "Nepali Sign Language",
    nativeName: "नेपाली साङ्केतिक भाषा",
    region: "South Asia",
    code: "nsp",
    spokenLang: "Nepali / English",
    speechLang: "en-IN",
  },

  // Americas
  {
    id: "asl",
    name: "American Sign Language",
    nativeName: "ASL",
    region: "Americas",
    code: "ase",
    spokenLang: "English",
    speechLang: "en-US",
  },
  {
    id: "lsm",
    name: "Mexican Sign Language",
    nativeName: "Lengua de Señas Mexicana",
    region: "Americas",
    code: "mfs",
    spokenLang: "Spanish",
    speechLang: "es-MX",
  },
  {
    id: "libras",
    name: "Brazilian Sign Language",
    nativeName: "Libras",
    region: "Americas",
    code: "bzs",
    spokenLang: "Portuguese",
    speechLang: "pt-BR",
  },
  {
    id: "lsa",
    name: "Argentine Sign Language",
    nativeName: "Lengua de Señas Argentina",
    region: "Americas",
    code: "aed",
    spokenLang: "Spanish",
    speechLang: "es-AR",
  },
  {
    id: "lsq",
    name: "Quebec Sign Language",
    nativeName: "Langue des signes québécoise",
    region: "Americas",
    code: "fcs",
    spokenLang: "French",
    speechLang: "fr-CA",
  },

  // Europe
  {
    id: "bsl",
    name: "British Sign Language",
    nativeName: "BSL",
    region: "Europe",
    code: "bfi",
    spokenLang: "English",
    speechLang: "en-GB",
  },
  {
    id: "dgs",
    name: "German Sign Language",
    nativeName: "Deutsche Gebärdensprache",
    region: "Europe",
    code: "gsg",
    spokenLang: "German",
    speechLang: "de-DE",
  },
  {
    id: "lsf",
    name: "French Sign Language",
    nativeName: "Langue des signes française",
    region: "Europe",
    code: "fsl",
    spokenLang: "French",
    speechLang: "fr-FR",
  },
  {
    id: "lis",
    name: "Italian Sign Language",
    nativeName: "Lingua dei Segni Italiana",
    region: "Europe",
    code: "ise",
    spokenLang: "Italian",
    speechLang: "it-IT",
  },
  {
    id: "lse",
    name: "Spanish Sign Language",
    nativeName: "Lengua de Signos Española",
    region: "Europe",
    code: "ssp",
    spokenLang: "Spanish",
    speechLang: "es-ES",
  },
  {
    id: "ngt",
    name: "Dutch Sign Language",
    nativeName: "Nederlandse Gebarentaal",
    region: "Europe",
    code: "dse",
    spokenLang: "Dutch",
    speechLang: "nl-NL",
  },
  {
    id: "rsl",
    name: "Russian Sign Language",
    nativeName: "Русский жестовый язык",
    region: "Europe",
    code: "rsl",
    spokenLang: "Russian",
    speechLang: "ru-RU",
  },
  {
    id: "pjms",
    name: "Polish Sign Language",
    nativeName: "Polski Język Migowy",
    region: "Europe",
    code: "pso",
    spokenLang: "Polish",
    speechLang: "pl-PL",
  },
  {
    id: "tid",
    name: "Turkish Sign Language",
    nativeName: "Türk İşaret Dili",
    region: "Europe",
    code: "tsm",
    spokenLang: "Turkish",
    speechLang: "tr-TR",
  },
  {
    id: "gsl",
    name: "Greek Sign Language",
    nativeName: "Ελληνική Νοηματική Γλώσσα",
    region: "Europe",
    code: "gss",
    spokenLang: "Greek",
    speechLang: "el-GR",
  },
  {
    id: "ssl-se",
    name: "Swedish Sign Language",
    nativeName: "Svenskt teckenspråk",
    region: "Europe",
    code: "swl",
    spokenLang: "Swedish",
    speechLang: "sv-SE",
  },
  {
    id: "nsl-no",
    name: "Norwegian Sign Language",
    nativeName: "Norsk tegnspråk",
    region: "Europe",
    code: "nsl",
    spokenLang: "Norwegian",
    speechLang: "nb-NO",
  },

  // East / Southeast Asia
  {
    id: "jsl",
    name: "Japanese Sign Language",
    nativeName: "日本手話",
    region: "East Asia",
    code: "jsl",
    spokenLang: "Japanese",
    speechLang: "ja-JP",
  },
  {
    id: "csl",
    name: "Chinese Sign Language",
    nativeName: "中国手语",
    region: "East Asia",
    code: "csl",
    spokenLang: "Chinese",
    speechLang: "zh-CN",
  },
  {
    id: "hksl",
    name: "Hong Kong Sign Language",
    nativeName: "香港手語",
    region: "East Asia",
    code: "hks",
    spokenLang: "Cantonese / English",
    speechLang: "zh-HK",
  },
  {
    id: "ksl",
    name: "Korean Sign Language",
    nativeName: "한국수어",
    region: "East Asia",
    code: "kvk",
    spokenLang: "Korean",
    speechLang: "ko-KR",
  },
  {
    id: "tsl",
    name: "Taiwanese Sign Language",
    nativeName: "台灣手語",
    region: "East Asia",
    code: "tss",
    spokenLang: "Mandarin",
    speechLang: "zh-TW",
  },
  {
    id: "filsl",
    name: "Filipino Sign Language",
    nativeName: "Wikang Pasenyas ng mga Pilipino",
    region: "Southeast Asia",
    code: "psp",
    spokenLang: "Filipino / English",
    speechLang: "en-PH",
  },
  {
    id: "bisindo",
    name: "Indonesian Sign Language",
    nativeName: "BISINDO",
    region: "Southeast Asia",
    code: "inl",
    spokenLang: "Indonesian",
    speechLang: "id-ID",
  },
  {
    id: "thsl",
    name: "Thai Sign Language",
    nativeName: "ภาษามือไทย",
    region: "Southeast Asia",
    code: "tsq",
    spokenLang: "Thai",
    speechLang: "th-TH",
  },
  {
    id: "vsl",
    name: "Vietnamese Sign Language",
    nativeName: "Ngôn ngữ ký hiệu Việt Nam",
    region: "Southeast Asia",
    code: "hab",
    spokenLang: "Vietnamese",
    speechLang: "vi-VN",
  },
  {
    id: "mysl",
    name: "Malaysian Sign Language",
    nativeName: "Bahasa Isyarat Malaysia",
    region: "Southeast Asia",
    code: "xml",
    spokenLang: "Malay / English",
    speechLang: "ms-MY",
  },

  // Middle East & Africa
  {
    id: "absl",
    name: "Arabic Sign Languages",
    nativeName: "لغات الإشارة العربية",
    region: "Middle East & Africa",
    code: "ar-sgn",
    spokenLang: "Arabic",
    speechLang: "ar-SA",
  },
  {
    id: "isri",
    name: "Israeli Sign Language",
    nativeName: "שפת הסימנים הישראלית",
    region: "Middle East & Africa",
    code: "isr",
    spokenLang: "Hebrew",
    speechLang: "he-IL",
  },
  {
    id: "sasl",
    name: "South African Sign Language",
    nativeName: "SASL",
    region: "Middle East & Africa",
    code: "sfs",
    spokenLang: "English / Afrikaans",
    speechLang: "en-ZA",
  },
  {
    id: "ethsl",
    name: "Ethiopian Sign Language",
    nativeName: "የኢትዮጵያ የምልክት ቋንቋ",
    region: "Middle East & Africa",
    code: "eth",
    spokenLang: "Amharic / English",
    speechLang: "en-US",
  },
  {
    id: "ghanasl",
    name: "Ghanaian Sign Language",
    nativeName: "Ghanaian Sign Language",
    region: "Middle East & Africa",
    code: "gse",
    spokenLang: "English",
    speechLang: "en-GH",
  },
  {
    id: "kenyasl",
    name: "Kenyan Sign Language",
    nativeName: "Lugha ya Ishara ya Kenya",
    region: "Middle East & Africa",
    code: "xki",
    spokenLang: "English / Swahili",
    speechLang: "en-KE",
  },
  {
    id: "nigsl",
    name: "Nigerian Sign Language",
    nativeName: "Nigerian Sign Language",
    region: "Middle East & Africa",
    code: "nsi",
    spokenLang: "English",
    speechLang: "en-NG",
  },

  // Oceania
  {
    id: "auslan",
    name: "Auslan",
    nativeName: "Australian Sign Language",
    region: "Oceania",
    code: "asf",
    spokenLang: "English",
    speechLang: "en-AU",
  },
  {
    id: "nzsl",
    name: "New Zealand Sign Language",
    nativeName: "NZSL",
    region: "Oceania",
    code: "nzs",
    spokenLang: "English / Māori",
    speechLang: "en-NZ",
  },

  // International
  {
    id: "is",
    name: "International Sign",
    nativeName: "International Sign",
    region: "International",
    code: "ils",
    spokenLang: "English",
    speechLang: "en-US",
  },
];

export const SIGN_REGIONS = [
  "South Asia",
  "Americas",
  "Europe",
  "East Asia",
  "Southeast Asia",
  "Middle East & Africa",
  "Oceania",
  "International",
] as const;

export function getSignLanguage(id: string) {
  return SIGN_LANGUAGES.find((l) => l.id === id) || SIGN_LANGUAGES[0];
}

export function languagesByRegion() {
  return SIGN_REGIONS.map((region) => ({
    region,
    languages: SIGN_LANGUAGES.filter((l) => l.region === region),
  })).filter((g) => g.languages.length > 0);
}
